#!D:/python/python.exe
print ("Content-type: text/html\n")
print("<html>")
print("<h1>Calculator</h1>")
print("<form name=input action=/cgi-bin/CGI/p2.py method=post>")
print("Num1: <input type=text name=Num1><br>")
print("Num2: <input type=text name=Num2><br>")
print("<p><input type=radio name=cal value=1> -")
print("&nbsp&nbsp")
print("<input type=radio name=cal value=2> +")
print("&nbsp&nbsp")
print("<input type=radio name=cal value=3> *")
print("&nbsp&nbsp")
print("<input type=radio name=cal value=4> \ <br>")
print("<p><input type=submit value=Calculate>")
print("</form>")
print("</html>")
